import React, { useState } from 'react';
import {
  FileText,
  Download,
  FileSpreadsheet,
  Eye,
  Plus,
  CheckCircle2,
} from 'lucide-react';
import { useWaterNetwork } from '../hooks/useWaterNetwork';
import { PageHeader } from '../components/PageHeader';
import { Modal } from '../components/Modal';
import { ReportItem } from '../types';

export const Reports: React.FC = () => {
  const { reports, generateCustomReport } = useWaterNetwork();
  const [previewReport, setPreviewReport] = useState<ReportItem | null>(null);
  const [toastMessage, setToastMessage] = useState<string | null>(null);

  const showToast = (msg: string) => {
    setToastMessage(msg);
    setTimeout(() => setToastMessage(null), 3500);
  };

  const handleDownloadPdf = (report: ReportItem) => {
    // Generate a clean text/document blob so the browser triggers a real file download
    const content = [
      `SMART WATER NETWORK — MUNICIPAL SCADA REPORT`,
      `=============================================`,
      `Report Name: ${report.name}`,
      `Report ID:   ${report.id}`,
      `Date:        ${report.date}`,
      `Author:      ${report.generatedBy}`,
      ``,
      `Executive Summary:`,
      report.summary,
      ``,
      `Key Metrics:`,
      ...report.metrics.map((m) => `- ${m.label}: ${m.value}`),
    ].join('\n');

    const blob = new Blob([content], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${report.name.toLowerCase().replace(/\s+/g, '_')}_${report.id}.txt`;
    a.click();
    URL.revokeObjectURL(url);
    showToast(`Downloaded "${report.name}" (${report.size})`);
  };

  const handleExportCsv = (report: ReportItem) => {
    const csvRows = [
      ['Report ID', 'Report Name', 'Date', 'Generated By', 'Metric', 'Value'].join(','),
      ...report.metrics.map((m) =>
        [
          report.id,
          `"${report.name}"`,
          `"${report.date}"`,
          `"${report.generatedBy}"`,
          `"${m.label}"`,
          `"${m.value}"`,
        ].join(',')
      ),
    ].join('\n');

    const blob = new Blob([csvRows], { type: 'text/csv;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${report.name.toLowerCase().replace(/\s+/g, '_')}.csv`;
    a.click();
    URL.revokeObjectURL(url);
    showToast(`Exported CSV for "${report.name}"`);
  };

  return (
    <div className="space-y-6">
      <PageHeader
        title="Reports"
        description="Generate and review water network performance reports."
        actions={
          <button
            onClick={() => {
              generateCustomReport('Daily Network Report');
              showToast('New Daily Network Report generated from live telemetry.');
            }}
            className="px-3.5 py-2 text-xs font-semibold text-white bg-sky-600 hover:bg-sky-700 rounded-lg transition-colors inline-flex items-center gap-1.5 whitespace-nowrap shrink-0"
          >
            <Plus className="w-4 h-4" />
            <span>Generate Snapshot Report</span>
          </button>
        }
      />

      {toastMessage && (
        <div className="bg-emerald-50 border border-emerald-200 text-emerald-900 px-4 py-3 rounded-xl text-xs font-medium flex items-center gap-2">
          <CheckCircle2 className="w-4 h-4 text-emerald-600 shrink-0" />
          <span>{toastMessage}</span>
        </div>
      )}

      {/* Report Cards Grid */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-5">
        {reports.map((report) => (
          <div
            key={report.id}
            className="bg-white border border-slate-200 rounded-xl p-5 flex flex-col justify-between space-y-5"
          >
            <div>
              <div className="flex items-start justify-between gap-3">
                <div className="flex items-start gap-3">
                  <div className="w-10 h-10 rounded-lg bg-sky-50 text-sky-700 flex items-center justify-center shrink-0">
                    <FileText className="w-5 h-5" />
                  </div>
                  <div>
                    <h2 className="text-base font-bold text-slate-900">{report.name}</h2>
                    <div className="flex flex-wrap items-center gap-2 text-xs text-slate-500 mt-1">
                      <span>Date: {report.date}</span>
                      <span aria-hidden="true">·</span>
                      <span>By: {report.generatedBy}</span>
                      <span aria-hidden="true">·</span>
                      <span className="font-mono text-slate-700">Format: {report.format}</span>
                    </div>
                  </div>
                </div>
                <span className="text-xs font-mono tabular-nums text-slate-400 shrink-0">
                  {report.id}
                </span>
              </div>

              <p className="text-xs text-slate-600 mt-3 leading-relaxed">{report.summary}</p>

              {/* Key metrics strip */}
              <div className="grid grid-cols-3 gap-2 mt-4 pt-3 border-t border-slate-100">
                {report.metrics.map((m, i) => (
                  <div key={i} className="bg-slate-50 rounded-lg p-2.5">
                    <div className="text-[11px] text-slate-500">{m.label}</div>
                    <div className="text-xs font-bold font-mono tabular-nums text-slate-900 mt-0.5">
                      {m.value}
                    </div>
                  </div>
                ))}
              </div>
            </div>

            {/* Required Buttons: [View] [Download PDF] [Export CSV] */}
            <div className="flex flex-wrap items-center gap-2 pt-3 border-t border-slate-100">
              <button
                onClick={() => setPreviewReport(report)}
                className="px-3.5 py-2 text-xs font-semibold text-slate-700 bg-slate-100 hover:bg-slate-200 rounded-lg transition-colors inline-flex items-center gap-1.5 whitespace-nowrap"
              >
                <Eye className="w-3.5 h-3.5" />
                <span>View</span>
              </button>
              <button
                onClick={() => handleDownloadPdf(report)}
                className="px-3.5 py-2 text-xs font-semibold text-white bg-sky-600 hover:bg-sky-700 rounded-lg transition-colors inline-flex items-center gap-1.5 whitespace-nowrap"
              >
                <Download className="w-3.5 h-3.5" />
                <span>Download PDF</span>
              </button>
              <button
                onClick={() => handleExportCsv(report)}
                className="px-3.5 py-2 text-xs font-semibold text-slate-700 border border-slate-200 hover:bg-slate-50 rounded-lg transition-colors inline-flex items-center gap-1.5 whitespace-nowrap"
              >
                <FileSpreadsheet className="w-3.5 h-3.5 text-emerald-600" />
                <span>Export CSV</span>
              </button>
            </div>
          </div>
        ))}
      </div>

      {/* Report Preview Modal */}
      <Modal
        isOpen={!!previewReport}
        onClose={() => setPreviewReport(null)}
        title={previewReport ? previewReport.name : 'Report Preview'}
        subtitle={
          previewReport
            ? `Generated on ${previewReport.date} by ${previewReport.generatedBy}`
            : ''
        }
        maxWidth="xl"
      >
        {previewReport && (
          <div className="space-y-4 text-sm">
            <div className="p-4 rounded-xl bg-slate-50 border border-slate-200">
              <div className="text-xs font-semibold text-slate-500 uppercase mb-1">
                Executive Audit Summary
              </div>
              <p className="text-slate-800 leading-relaxed text-xs">
                {previewReport.summary}
              </p>
            </div>

            <div className="grid grid-cols-3 gap-3">
              {previewReport.metrics.map((m, idx) => (
                <div key={idx} className="p-3.5 rounded-xl border border-slate-200 bg-white">
                  <div className="text-xs text-slate-500">{m.label}</div>
                  <div className="text-base font-bold font-mono tabular-nums text-slate-900 mt-1">
                    {m.value}
                  </div>
                </div>
              ))}
            </div>

            <div className="flex justify-end gap-2 pt-3 border-t border-slate-200">
              <button
                onClick={() => handleExportCsv(previewReport)}
                className="px-3.5 py-2 text-xs font-medium text-slate-700 bg-slate-100 hover:bg-slate-200 rounded-lg"
              >
                Export CSV
              </button>
              <button
                onClick={() => handleDownloadPdf(previewReport)}
                className="px-4 py-2 text-xs font-semibold text-white bg-sky-600 hover:bg-sky-700 rounded-lg"
              >
                Download PDF
              </button>
            </div>
          </div>
        )}
      </Modal>
    </div>
  );
};
